### ISSUE TITLE
Translate from text to Java

### ISSUE THREAD

**Issue by mellahysf** [neulab/NL2code#10]
Hello,

I want to use this project to translate from text to Java code, so i have some questions about that : 
It is possible ? how ? 
There is a corpus (text to java code) that can be used ? 

Thank youk.

**Comment by laleye** [comment]
Hi
Have you found a corpus to translate a text 2 java code corpus, if yes, I am interested.

**Comment by Graydyn** [comment]
Even if there were a corpus for text->java (and I'm pretty sure there isn't) have you guys thought about how much harder that would be?  This project was extremely ambitious even when working with Python, and Python is practically sudocode already.

Also, what would be the intended purpose of changing the language?  Are you getting that this project was more of a proof of concept?  You aren't going to get useful code out of it.

**Comment by laleye** [comment]
@Graydyn I fully understand your remark, but the method proposed in the paper seems to be generic according to the description of the authors ... in this case, my goal is to experiment with this method on other programming languages that I meet in the uses cases of a project I'm working on.

**Comment by neubig** [comment]
I agree this is harder.

We did extract a parallel English-Java corpus in our paper here: https://arxiv.org/pdf/1805.08949.pdf

However, this is not included in our conala data (https://conala-corpus.github.io), because we had to do an additional amount of manual curation to create test sets, which we didn't have time/money to do for Java.

If you are interested in creating a Java parser you will (1) need a corpus, which could potentially be created but it'd be some amount of work, and (2) a parser capable of supporting Java. If you got (1), I'd suggest using our newer version of our language-to-code parser, tranX to support 2: https://github.com/pcyin/tranX

If you'd like you could create an issue there, although I doubt we'll be able to do it ourselves. Contributions would certainly be welcome!

**Comment by pcyin** [comment]
Hi @Graydyn @mellahysf, since this repo is no longer maintained, I would suggest using our [tranX](https://github.com/pcyin/tranX) parser, a updated version of this repo and has the flexibility to support different programming languages. I internally tested tranX to generate C# code and it worked. Considering that Java and C# has similar level of syntactic complexity, it could scale to Java as well as long as you have a corpus of text->Java code. Let me know if you have any further questions!

**Comment by mellahysf** [comment]
Hi all,
@laleye  no i don't found any corpus text->java :/ 
@pcyin @neubig  Thank you very much, i will test your new project tranX, it's very interested. 
@pcyin can you please send me elements for C# that you tested ?
